#  _               _
# | |__   __ _ ___| |__  _ __ ___
# | '_ \ / _` / __| '_ \| '__/ __|
# | |_) | (_| \__ \ | | | | | (__
# |_.__/ \__,_|___/_| |_|_|  \___|

# source aliases
source ~/dotfiles/bash/aliases
# source prompt
source ~/dotfiles/bash/prompt

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth
# append to the history file, don't overwrite it
shopt -s histappend
# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000000
HISTFILESIZE=1000000
# history ignores
HISTIGNORE='ls:bg:fg:history'
# history Date Time Format
HISTTIMEFORMAT='%F %T '
# use one command per line History
shopt -s cmdhist

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# source exports
source ~/dotfiles/bash/exports
